import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Layout from "./components/Layout";
import Animated from "./components/animated/Animated";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Full-Stack Developer",
  description: "Generated by Voronko Denis",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={`page bg-site text-white bg-cover bg-no-repeat ${sora.variable} font-sora relative`}
      >
        <Toaster />
        <Layout />
        <Animated>{children}</Animated>
      </body>
    </html>
  );
};
export default RootLayout;
